Farm Staking Proxy Legacy SC
multiversx/mx-exchange-sc pull request #928
Opened 2024-06-23 23:33 UTC by psorinionut

2024-06-27 07:22 UTC, dorin-iancu approved these changes

2024-06-28 08:46 UTC, CostinCarabas submitted a review, later dismissed

2024-07-01 15:46 UTC, ovidiuolteanu requested changes
Please add the [upgrade] endpoint as well.

2024-07-02 06:57 UTC, CostinCarabas approved these changes

2024-07-03 08:16 UTC, ovidiuolteanu approved these changes

2024-07-03 08:34 UTC, merged